# Generated by Django 5.0.1 on 2024-01-21 12:40

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('utility', '0002_property_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rproject_Images',
            new_name='Images',
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('min_price', models.IntegerField(blank=True, default=0, null=True)),
                ('max_price', models.IntegerField(blank=True, default=0, null=True)),
                ('min_area', models.CharField(blank=True, max_length=50, null=True)),
                ('max_area', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=5000)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=25)),
                ('project_size', models.CharField(max_length=255)),
                ('lanch_date', models.DateField()),
                ('totle_unit', models.CharField(max_length=2)),
                ('total_tower', models.CharField(max_length=2)),
                ('construction_status', models.CharField(choices=[('Under Construction', 'Under Construction'), ('New Launch', 'New Launch'), ('Partially Ready To Move', 'Partially Ready To Move'), ('Ready To Move', 'Ready To Move'), ('Deleverd', 'Deleverd')], max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('amenities', models.ManyToManyField(to='utility.amenities')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.city')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.developer')),
                ('home_lone', models.ManyToManyField(to='utility.bank')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.locality')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.project')),
                ('possession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.possession_in')),
                ('propert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.property_type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='images',
            name='Residential_Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.DeleteModel(
            name='Residential_Project',
        ),
    ]
