# Generated by Django 5.0.1 on 2024-01-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_rproject_images_images_project_and_more'),
        ('utility', '0003_area_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='status',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='status',
        ),
        migrations.AddField(
            model_name='city',
            name='featured_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='developer',
            name='featured_builder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locality',
            name='featured_locality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='slider',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='amenities',
            field=models.ManyToManyField(blank=True, null=True, to='utility.amenities'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='home_lone',
            field=models.ManyToManyField(blank=True, null=True, to='utility.bank'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lanch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='Floor_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet_area', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('floor_plan', models.ImageField(blank=True, upload_to='images/')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('arey_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.area_type')),
                ('bed_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.bedroom')),
            ],
        ),
    ]
