# Generated by Django 5.0.1 on 2024-01-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_city_status_remove_locality_status_and_more'),
        ('utility', '0003_area_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '1. Project'},
        ),
        migrations.AddField(
            model_name='floor_plans',
            name='bath_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.bathroom'),
        ),
        migrations.AddField(
            model_name='floor_plans',
            name='bolconis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.bolconis'),
        ),
    ]
