# Generated by Django 5.0.1 on 2024-01-27 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responce_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commercial_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.commercial_project')),
            ],
            options={
                'verbose_name_plural': '2. Commercial Project',
            },
        ),
        migrations.CreateModel(
            name='Residential_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agency')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.residential_project')),
            ],
            options={
                'verbose_name_plural': '1. Residential Project',
            },
        ),
        migrations.CreateModel(
            name='Developer_Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.developer')),
                ('responce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_visit.responce_type')),
            ],
            options={
                'verbose_name_plural': '4. Developer',
            },
        ),
        migrations.CreateModel(
            name='Agency_Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agency')),
                ('responce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_visit.responce_type')),
            ],
            options={
                'verbose_name_plural': '3. Agency',
            },
        ),
    ]
