# Generated by Django 5.0.1 on 2024-02-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='testmonial_bg',
            field=models.ImageField(blank=True, upload_to='logo/'),
        ),
    ]
