# Generated by Django 5.0.1 on 2024-02-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_setting_testmonial_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_team',
            name='facebook',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='our_team',
            name='instagram',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='our_team',
            name='pinterest',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='our_team',
            name='twitter',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='our_team',
            name='youtube',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
