# Generated by Django 5.0.1 on 2024-02-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_our_team_facebook_our_team_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
