# Generated by Django 5.0.1 on 2024-01-27 08:55

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('utility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commercial_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('min_price', models.IntegerField(blank=True, default=0, null=True)),
                ('max_price', models.IntegerField(blank=True, default=0, null=True)),
                ('min_area', models.CharField(blank=True, max_length=50, null=True)),
                ('max_area', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('Occupancy_Certificate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True)),
                ('Commencement_Certificate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True)),
                ('status', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=25, null=True)),
                ('project_size', models.CharField(blank=True, max_length=255, null=True)),
                ('lanch_date', models.DateField(blank=True, null=True)),
                ('totle_unit', models.CharField(max_length=2)),
                ('total_tower', models.CharField(max_length=2)),
                ('construction_status', models.CharField(choices=[('Under Construction', 'Under Construction'), ('New Launch', 'New Launch'), ('Partially Ready To Move', 'Partially Ready To Move'), ('Ready To Move', 'Ready To Move'), ('Deleverd', 'Deleverd')], max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('slider', models.BooleanField(default=False)),
                ('featured_project', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('amenities', models.ManyToManyField(blank=True, to='utility.amenities')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.developer')),
                ('home_lone', models.ManyToManyField(blank=True, to='utility.bank')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.commercial_project')),
                ('possession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.possession_in')),
                ('propert_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.commercial_property_type')),
            ],
            options={
                'verbose_name_plural': '2. Commercial Project',
            },
        ),
        migrations.CreateModel(
            name='Commercial_Project_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rate', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.commercial_project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '4. Commercial Comment',
            },
        ),
        migrations.CreateModel(
            name='Commercial_Project_Floor_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet_area', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('floor_plan', models.ImageField(blank=True, upload_to='images/')),
                ('arey_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.area_type')),
                ('bath_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.bathroom')),
                ('bolconis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.bolconis')),
                ('commercial_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.commercial_project')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.floor')),
            ],
            options={
                'verbose_name_plural': '7. Commercial Project Floor Plan',
            },
        ),
        migrations.CreateModel(
            name='Commercial_Project_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('commercial_project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.commercial_project')),
            ],
            options={
                'verbose_name_plural': '8. Commercial Project Images',
            },
        ),
        migrations.CreateModel(
            name='Residential_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('min_price', models.IntegerField(blank=True, default=0, null=True)),
                ('max_price', models.IntegerField(blank=True, default=0, null=True)),
                ('min_area', models.CharField(blank=True, max_length=50, null=True)),
                ('max_area', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('Occupancy_Certificate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True)),
                ('Commencement_Certificate', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True)),
                ('status', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=25, null=True)),
                ('project_size', models.CharField(blank=True, max_length=255, null=True)),
                ('lanch_date', models.DateField(blank=True, null=True)),
                ('totle_unit', models.CharField(max_length=2)),
                ('total_tower', models.CharField(max_length=2)),
                ('construction_status', models.CharField(choices=[('Under Construction', 'Under Construction'), ('New Launch', 'New Launch'), ('Partially Ready To Move', 'Partially Ready To Move'), ('Ready To Move', 'Ready To Move'), ('Deleverd', 'Deleverd')], max_length=25)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('slider', models.BooleanField(default=False)),
                ('featured_project', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('amenities', models.ManyToManyField(blank=True, to='utility.amenities')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.city')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.developer')),
                ('home_lone', models.ManyToManyField(blank=True, to='utility.bank')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.locality')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='project.residential_project')),
                ('possession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.possession_in')),
                ('propert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.residential_property_type')),
            ],
            options={
                'verbose_name_plural': '1. Residential Project',
            },
        ),
        migrations.CreateModel(
            name='Residential_Project_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rate', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.residential_project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '3. Residential Comment',
            },
        ),
        migrations.CreateModel(
            name='Residential_Project_Floor_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet_area', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('floor_plan', models.ImageField(blank=True, upload_to='images/')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.residential_project')),
                ('arey_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.area_type')),
                ('bath_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.bathroom')),
                ('bed_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.bedroom')),
                ('bolconis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.bolconis')),
            ],
            options={
                'verbose_name_plural': '6. Residential Project Flor Plan',
            },
        ),
        migrations.CreateModel(
            name='Residential_Project_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.residential_project')),
            ],
            options={
                'verbose_name_plural': '5. Residential Project Images',
            },
        ),
    ]
