# Generated by Django 5.0.1 on 2024-07-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_commercial_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential_project',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
