# Generated by Django 5.0.1 on 2024-01-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_fine_from'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fine_from',
            options={'verbose_name_plural': '20. Fine_From'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name_plural': '18. Locality'},
        ),
        migrations.AlterModelOptions(
            name='social_site',
            options={'verbose_name_plural': '19. Social Site'},
        ),
        migrations.AlterModelOptions(
            name='willing_to_rent_out',
            options={'verbose_name_plural': '15. Willing To Rent Out'},
        ),
    ]
