# Generated by Django 5.0.1 on 2024-01-27 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('utility', '0002_fine_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='find_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.fine_from'),
        ),
        migrations.AddField(
            model_name='developer',
            name='find_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.fine_from'),
        ),
    ]
