# Generated by Django 5.0.1 on 2024-01-28 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_agency_google_map_agency_web_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer_error',
            old_name='agency',
            new_name='developer',
        ),
        migrations.CreateModel(
            name='Developer_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('comment', models.CharField(max_length=1000)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agency')),
            ],
            options={
                'verbose_name_plural': '8. Agency Meeting',
            },
        ),
    ]
