# Generated by Django 5.0.1 on 2024-01-28 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_agency_developer_error_developer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer_meeting',
            options={'verbose_name_plural': '7. Developer Meeting'},
        ),
        migrations.RemoveField(
            model_name='developer_meeting',
            name='agency',
        ),
        migrations.AddField(
            model_name='developer_meeting',
            name='developer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='user.developer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer_meeting',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='developer_meeting',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Agency_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.agency')),
            ],
            options={
                'verbose_name_plural': '8. Agency Meeting',
            },
        ),
    ]
