# Generated by Django 5.0.1 on 2024-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_agency_error_create_at_agency_error_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
