# Generated by Django 5.0.1 on 2024-05-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_agency_title_alter_developer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
